site_title = "MyArxiv"
limit_days = 7
cache_url = "https://lijjzz.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.DC"
title = "Container scheduling"

[[sources]]
limit = 150
category = "cs.AI"
title = "Some new methods"

[[sources]]
limit = 150
category = "cs.LG"
title = "Some new methods"



[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
